/*
  新手可修改区：
  1. 修改 modules 里的 title / icon，即可调整左侧栏目名称和图标。
  2. 修改 factoryData / tasks / ideas 等数据，即可替换演示内容。
  3. 每个卡片上的「编辑」按钮可在页面内直接改数据，浏览器会自动记住。
*/
const modules = [
  ['dashboard', '▦', '主控台', '今日生产概览'], ['positioning', '◎', 'IP定位', '品牌与账号定位'],
  ['viral', '◈', '爆款拆解库', '爆款内容结构'], ['inspiration', '✦', '灵感库', '随手收集灵感'],
  ['topics', '◉', '选题库', '选题排期与进度'], ['scripts', '▤', '文案库', '文案与标题'],
  ['execution', '▣', '视频执行库', '素材、配音与剪辑'], ['analytics', '▥', '数据分析库', '账号数据看板'],
  ['review', '↻', '复盘库', '经验沉淀']
];
const defaults = {
  factoryData: [{ city: '东莞', code: 'DG', color: '#7367f0', videos: 12, rate: '86%', status: '顺畅' }, { city: '越南平阳', code: 'VN', color: '#20b991', videos: 8, rate: '72%', status: '跟进中' }],
  tasks: [{ title: '汽车线束 · 生产过程实拍', tag: '东莞', state: '待审核', percent: 80, owner: '陈宇' }, { title: '越南工厂 · 车间效率揭秘', tag: '平阳', state: '剪辑中', percent: 55, owner: 'Anna' }, { title: '为什么客户都来工厂验货？', tag: '东莞', state: '待配音', percent: 35, owner: '林小玲' }],
  ideas: ['客户验厂时最爱问的 3 个问题', '一条产线一天能生产多少？', '中越工厂如何协同交付？'],
  topics: ['带你看完一个订单的诞生', '越南工厂的一天', '工厂老板不说的降本方法'],
  scripts: [{ title: '客户为什么一定要来验厂？', stage: '待确认', words: 318 }, { title: '东莞工厂的 60 秒日常', stage: '可拍摄', words: 265 }],
  positioningText: '我们是连接东莞与越南平阳的制造伙伴，为品牌客户提供稳定、高效、可追溯的生产交付。'
};
let data = JSON.parse(localStorage.getItem('videoFactoryData') || 'null') || defaults;
let active = 'dashboard';
const $ = s => document.querySelector(s);
function save() { localStorage.setItem('videoFactoryData', JSON.stringify(data)); }
function nav() { $('#sidebar-nav').innerHTML = modules.map(([id, icon, title]) => `<button class="nav-item ${id === active ? 'active' : ''}" data-page="${id}"><span>${icon}</span>${title}</button>`).join(''); document.querySelectorAll('[data-page]').forEach(b => b.onclick = () => render(b.dataset.page)); }
function metric(label, value, change, tone = 'purple') { return `<article class="metric-card"><div class="metric-icon ${tone}">◌</div><div><span>${label}</span><strong>${value}</strong><small class="${change.includes('+') ? 'positive' : ''}">${change}</small></div></article>`; }
function empty(title, text, action='新建内容') { return `<div class="empty"><div>◌</div><h3>${title}</h3><p>${text}</p><button class="primary" onclick="openEditor('${action}', '把想法写在这里…', 'ideas')">+ ${action}</button></div>`; }
function dashboard() { return `<div class="page dashboard"><section class="welcome"><div><p>星期二，下午好 👋</p><h2>今天也要高效产出好内容</h2><span>东莞 & 越南平阳 · 视频生产正在协同推进</span></div><button class="primary" onclick="openQuickCreate()">+ 创建新视频</button></section><section class="metric-grid">${metric('本周发布视频', '20', '较上周 +25%')}${metric('累计播放量', '28.6万', '较上周 +18.4%', 'orange')}${metric('平均完播率', '61.8%', '较上周 +4.2%', 'green')}${metric('待处理任务', '7', '2 个需要优先处理', 'blue')}</section><section class="content-grid"><article class="panel tasks"><div class="panel-head"><div><h3>今日视频生产</h3><p>从选题到发布，跟进每一条视频</p></div><button class="text-btn" onclick="render('execution')">查看全部 →</button></div>${data.tasks.map((t,i) => `<div class="task-row"><div class="task-main"><strong>${t.title}</strong><span><b class="tag">${t.tag}</b> · ${t.owner}</span></div><div class="progress"><i style="width:${t.percent}%"></i></div><span class="state ${t.state}">${t.state}</span><button class="more" onclick="editTask(${i})">···</button></div>`).join('')}</article><article class="panel factory"><div class="panel-head"><div><h3>双工厂协同</h3><p>实时查看两地生产状态</p></div><button class="text-btn" onclick="openEditor('编辑工厂信息', data.factoryData.map(x=>x.city).join('、'), 'factory')">编辑</button></div>${data.factoryData.map(f => `<div class="factory-row"><span class="factory-logo" style="background:${f.color}">${f.code}</span><div><strong>${f.city}工厂</strong><span>本周已产出 ${f.videos} 条视频</span></div><div class="factory-number"><strong>${f.rate}</strong><span>${f.status}</span></div></div>`).join('')}</article></section><section class="panel flow"><div class="panel-head"><div><h3>内容生产漏斗</h3><p>本周内容生产进度</p></div><button class="text-btn" onclick="render('analytics')">数据详情 →</button></div><div class="funnel">${[['灵感收集',32],['选题确定',18],['文案完成',15],['拍摄剪辑',11],['发布上线',20]].map(([n,v],i)=>`<div><span class="step-num">0${i+1}</span><strong>${v}</strong><small>${n}</small><i></i></div>`).join('')}</div></section></div>`; }
function libraryPage(type, title, description, items, key) { return `<div class="page"><section class="library-hero"><div><p>${description}</p><h2>${title}</h2></div><button class="primary" onclick="openEditor('新增${title}', '', '${key}')">+ 新增${title.replace('库','')}</button></section><section class="panel list-panel">${items.length ? items.map((x,i) => `<div class="library-row"><span class="row-icon">${type}</span><div><strong>${typeof x === 'string' ? x : x.title}</strong><small>${typeof x === 'string' ? '待完善 · 点击编辑补充内容' : `${x.words} 字 · ${x.stage}`}</small></div><button class="secondary" onclick="openEditor('编辑内容', '${typeof x === 'string' ? x : x.title}', '${key}', ${i})">编辑</button></div>`).join('') : empty(`还没有${title}`, '点击右上角按钮，先录入第一条内容。')}</section><aside class="tip"><strong>小白操作提示</strong><p>新增或编辑后会自动保存到当前浏览器。想彻底换内容，可在「系统设置」中重置演示数据。</p></aside></div>`; }
function execution() { return `<div class="page"><section class="library-hero"><div><p>视频执行库</p><h2>把选题变成可发布的视频</h2></div><button class="primary" onclick="openQuickCreate()">+ 创建新视频</button></section><div class="execution-grid">${[['01','素材库管理','按工厂、产品、场景管理图片与视频','管理素材'],['02','AI 文案编辑','一键生成口播稿与分镜脚本','编辑文案'],['03','语音配音','选择声音、试听并导出音频','开始配音'],['04','自动剪辑','组合素材、字幕与配音生成初版视频','开始剪辑']].map(([n,t,d,a])=>`<article class="exec-card"><span>${n}</span><h3>${t}</h3><p>${d}</p><button class="secondary" onclick="toast('${a}入口已预留，可在这里接入您的工具')">${a} →</button></article>`).join('')}</div><section class="panel material"><div class="panel-head"><div><h3>素材库</h3><p>最近上传的工厂实拍素材</p></div><button class="text-btn" onclick="toast('素材上传入口已预留')">+ 上传素材</button></div><div class="material-grid">${['生产线近景','质检工位','客户验货','仓库发货'].map((n,i)=>`<div class="material-thumb t${i}"><span>▶</span><strong>${n}</strong><small>东莞工厂 · 00:18</small></div>`).join('')}</div></section></div>`; }
function analytics() { return `<div class="page"><section class="library-hero"><div><p>数据分析库</p><h2>让每一次发布都有依据</h2></div><button class="secondary" onclick="toast('已导出本周数据报表')">导出报表</button></section><section class="metric-grid">${metric('总曝光', '486,200', '本周 +18.4%')}${metric('互动次数', '12,384', '评论 +326', 'orange')}${metric('新增线索', '46', '东莞 29 · 平阳 17', 'green')}${metric('高潜视频', '6', '建议优先复盘', 'blue')}</section><section class="panel chart"><div class="panel-head"><div><h3>近 7 天播放趋势</h3><p>东莞与平阳账号汇总</p></div><span class="legend">● 播放量</span></div><div class="bars">${[45,60,38,76,56,88,69].map((h,i)=>`<div><i style="height:${h}%"></i><small>${['周二','周三','周四','周五','周六','周日','今日'][i]}</small></div>`).join('')}</div></section></div>`; }
function positioning() { return `<div class="page"><section class="library-hero"><div><p>IP定位</p><h2>先定义你要让客户记住什么</h2></div><button class="primary" onclick="openEditor('编辑 IP 定位', data.positioningText, 'positioning')">编辑定位</button></section><section class="panel positioning"><label>目标客户<strong>需要稳定产能与跨区域协同的品牌采购、贸易商</strong></label><label>IP 人设<strong>懂制造、讲效率、真实可信的工厂主理人</strong></label><label>核心定位<strong>${data.positioningText}</strong></label><label>内容基调<strong>专业、真实、有温度；多展示人、产品和真实现场</strong></label></section><aside class="tip"><strong>怎么修改？</strong><p>点击右上角「编辑定位」，把您的行业、产品和优势替换进去。之后生成选题和文案都会以此为基础。</p></aside></div>`; }
function render(id='dashboard') { active=id; const module=modules.find(x=>x[0]===id); $('#page-title').textContent=module[2]; $('#page-eyebrow').textContent=module[3]; nav(); const views={dashboard,positioning,viral:()=>libraryPage('◈','爆款拆解库','记录值得学习的对标账号、视频和结构', ['3 秒展示产品解决的问题','工厂实拍 + 客户反馈 + 交付结果','数字化车间的沉浸式参观'], 'ideas'), inspiration:()=>libraryPage('✦','灵感库','随时收集刷到的好内容和客户问题',data.ideas,'ideas'), topics:()=>libraryPage('◉','选题库','从灵感中挑出本周要拍的内容',data.topics,'topics'), scripts:()=>libraryPage('▤','文案库','管理口播稿、标题和分镜脚本',data.scripts,'scripts'),execution,analytics,review:()=>libraryPage('↻','复盘库','沉淀高播放、获客和踩坑经验',['《车间效率揭秘》：前 3 秒必须先给结果','客户验货内容：真实问答比口播更容易被信任'],'ideas')}; $('#page-content').innerHTML=views[id](); }
function toast(message) { const el=$('#toast'); el.textContent=message; el.classList.remove('hidden'); setTimeout(()=>el.classList.add('hidden'),2500); }
function openEditor(title, value='', key='ideas', index=null) { $('#modal').innerHTML=`<button class="close" onclick="closeModal()">×</button><p class="modal-eyebrow">可视化修改入口</p><h2>${title}</h2><label>内容名称或描述<textarea id="editor-input" rows="5">${value}</textarea></label><p class="modal-help">小白提示：直接改上面的文字，点击保存即可。这里的数据保存在当前浏览器。</p><button class="primary full" id="save-editor">保存修改</button>`; $('#modal-backdrop').classList.remove('hidden'); $('#save-editor').onclick=()=>{const text=$('#editor-input').value.trim(); if(!text) return toast('请先输入内容'); if(key==='positioning') data.positioningText=text; else if(key==='factory') toast('工厂信息的可视化编辑入口已预留；名称可在 app.js 的 defaults 中替换。'); else { if(!data[key]) data[key]=[]; if(index !== null) { if(typeof data[key][index]==='string') data[key][index]=text; else data[key][index].title=text; } else data[key].unshift(key==='scripts'?{title:text,stage:'待确认',words:Math.max(80,text.length)}:text); } save(); closeModal(); render(active); toast('已保存，可继续修改'); }; }
function closeModal(){ $('#modal-backdrop').classList.add('hidden'); }
function editTask(i){ const t=data.tasks[i]; openEditor('编辑视频任务',t.title,'tasks',i); }
function openQuickCreate(){ $('#modal').innerHTML=`<button class="close" onclick="closeModal()">×</button><p class="modal-eyebrow">新建视频</p><h2>从一个选题开始</h2><label>视频主题<input id="new-task" placeholder="例如：客户为什么选择我们？" autofocus></label><div class="create-options"><button onclick="createTask('东莞')">东莞工厂</button><button onclick="createTask('平阳')">越南平阳</button></div><p class="modal-help">创建后会自动放进「视频执行库」，可继续补充素材、文案和配音。</p></div>`; $('#modal-backdrop').classList.remove('hidden'); }
function createTask(factory){ const title=$('#new-task').value.trim() || '新建工厂短视频'; data.tasks.unshift({title,tag:factory,state:'待策划',percent:10,owner:'我'}); save(); closeModal(); render('dashboard'); toast('视频任务已创建'); }
function openSettings(){ $('#modal').innerHTML=`<button class="close" onclick="closeModal()">×</button><p class="modal-eyebrow">系统设置</p><h2>演示数据与自定义</h2><p class="modal-help">要长期替换工厂、任务和栏目，请按《视频自动剪视频系统文档》修改 app.js 顶部的 defaults 和 modules。重置会清除本浏览器内新增或编辑的内容。</p><button class="secondary full" id="reset-data">恢复初始演示数据</button>`; $('#modal-backdrop').classList.remove('hidden'); $('#reset-data').onclick=()=>{localStorage.removeItem('videoFactoryData'); data=JSON.parse(JSON.stringify(defaults)); closeModal(); render(active); toast('已恢复初始演示数据');}; }
$('#open-settings').onclick=openSettings; $('#start-guide').onclick=()=>toast('请按：IP定位 → 灵感 → 选题 → 文案 → 视频执行 → 数据复盘 的顺序操作'); $('#today-btn').onclick=()=>toast('日期筛选入口已预留'); $('#modal-backdrop').onclick=e=>{ if(e.target.id==='modal-backdrop') closeModal(); }; render();
